apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:MmRbEtL4/qxQ,iv:6JR73+1bfX92RQpmb5bGBIs1cj8rngKR2+oz4tUsRZc=,tag:fb7o2jFebuoo05lX8xr6ag==,type:str]
    admin-user: ENC[AES256_GCM,data:1GnTU0M=,iv:NJ4VKP5XZMTE9dyZ1NNp4nB2V4oju/C1CZpeQTDwn7Y=,tag:5UfSYci0esqhPeJkekGmkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7f2np2gjaga5zusg7tltae997ft8ha4zglm5qftn3snx8xyefrscdxg7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCangra3FKVFRWSGF1NENG
            Z0hKU2o4TEVTb1JWOEJwaXJwei9yQkNmMXlrCk1NMGFXaTh2bnlscXhGREFZNE5Q
            UkZzYi9HQi8yYVhHMkt5eG5aUDZWUDgKLS0tIFJqamhIMW14ZE9qUHk4Y1FZSzYr
            YlRXYnJXZDk1RVUvSWFLU2ZheC8zMjAKUEWRA+UAKvEd1NbHJFDpeU7qd/GqsABl
            qahcz4dofQ1NIvQ627anVONnULfcSVePZwJcWalMejocTERK3U9XzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T19:53:51Z"
    mac: ENC[AES256_GCM,data:7GeS+BAqGD7kVovNpUCgJGFMctZFr5CVQlS1BL+gZxKXJJMbzwaJ1Ogpz9wTV4Xt23tg7YHP4NcTbF3YaCXvPVgWIr9wvY3eRUK71+FISNvSGUzPfrRJxsfJLNDsfLvcUdgBN2ZxscvlUG1bigjq2mlIZrlgV+v7m4qe5kUf/7g=,iv:C+fUzLGpYOxG5Gzupwig+EiRXjLd9z/s1JkeHZt9Q+Y=,tag:CiIs5osX3No+I4iuhxYttQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
