apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+xryiu616eoK7nqEfBO3zc5DYBMi70SH,iv:fmhCObzz7r+jJ+pNHvbHuZP+2LlAGXCfXsa3/lXSazw=,tag:OFV7txBepCahu/m9ZTp0kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7f2np2gjaga5zusg7tltae997ft8ha4zglm5qftn3snx8xyefrscdxg7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUFpiZDNpd2FSWXJMdURp
            dk90aG82SGJvZzIwV2JQMW9EQUZJelFMcWs0CmdtZEtHMTRuUmFFRC9TM0lGQmlp
            U3V4aVpUUjhmWVlPYlFBZVRpYnpYWEEKLS0tIDRjMUtDS0dnYWR6NmhzZ2JNYXFo
            ZFZ4cWFYRnBVM3g3cFFsMVFybkl2S1kKtAtdgfxqcQN/vCj6TKTKt3Lxc+TkrrWj
            4rWQTLAClbGLqPQdAYlauBi7sf7REiIUvkWPHvUCLM56C9kxYWcJTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T21:17:36Z"
    mac: ENC[AES256_GCM,data:1ZlQfcSiGErV9cqCmAsLCGRu9BVrPovhtnWvKesuOPxwFL+dMVmj/B/ZpDZKc3q3BaVj3R5iZDAUuYfQ5kZMgTDT/xx7z76JOe3M8hGpiyLpBVJfCsNhR7uFn+kXGhQMR0asiDxsz/PQHBbnwbOcRvV/YcmWdBMhxvT/V0sK1Ro=,iv:gd6oKW0NUyybb13CKWBvVqLnUZq5NjZAmrVT9XQNBAs=,tag:wIeHuLoE+xzrMK/JN5A5/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
