apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Phzuya/L/FISMf2r,iv:laK2XlXeCu+xumg+xsNMzyVgUDG6GcdxrPKcwZDd/fY=,tag:UwZ0TXnemmXgSmDZL0lopQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7f2np2gjaga5zusg7tltae997ft8ha4zglm5qftn3snx8xyefrscdxg7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSSs3T2JZSGIrQzVaaUJU
            RGQveUh2NHd1K0hxVm95ODVsRkVDWlZMQldBCjgvMEZnbVBHNkVGdmtZTHh6amxC
            SkhDM2VsSEJuUGlmUXVZMWR3clVORlUKLS0tIDNZOE03azZxdEJjeGR2KzFSZnVD
            QXFXUDFKaHIvWW5majlRRWdiOHA0YkkK4Vvbg2dEf/CmmQhhJWzQFXu6ah5E6IdU
            EiY4py5HswSD3fDcs/HdygTFu9XcElIpjRzxX6iH20XRe+rrlWmviw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T19:53:48Z"
    mac: ENC[AES256_GCM,data:vaWbT35Vh4pVzAQyUFXvQLpv5axvdfrUGi0uwNpGEGpfTHDwWkBCncjZGhwpx25OaECH1UteaZ5ZDMp5YvBuSjLSC1xjbghO8j/6FEEIrBUJmjr+hk5TNI78QIjecZPJSILSdG3MCwuz5vMXsMUhRT6R+wAboo0xd8U4VC3Spi8=,iv:qkEKsU+DoXixiVlzx4OCUdyIENJSxlg8urX5XAXlzs0=,tag:5dm4sNldxH+8cTJMl+hVcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
