apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Dyxqx1qkv5iUwGWy/bKaQTJ9LmYzzFp1Ar8Dz9S2b2qtNkj2,iv:R4ZZ/L8STc/sAsI3fmIfFPqaQoeiu0re7dDxmlGWHVM=,tag:ROi+SXHfLIqUp1VaQValFQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:8x8eRhp70TMBh4hKZMyiD3j53p78n+//57mMNHBH9esbyMh/BtBm5ipXaAFQmsL800XdoIaaTCv9Qk1Ufa5zgPU1NGI0hGHeGCCaWzTClLLQsluZRkd2kEDBXtmOv5+sQTmvnM8b84M52tkH4i3ceLWQE1nGdkZC6J05iUzk6NBt8XZ+i11lNKrS9XGQJIRZ+qE5RaoKHdsTcm//iWfCwY8qOkefmXXVTypuHMB01w==,iv:SnL+6z0KbkFnKPI/gUYpFg3Xm7BZ2+cB5p/Cv5lRitI=,tag:YPb4nV22uw+MU5sPfXPs0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7f2np2gjaga5zusg7tltae997ft8ha4zglm5qftn3snx8xyefrscdxg7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWDM5YnhkcDFYbEROTVBN
            L0dKNXJpa1NKb0ZXYkZkTmZuNkJISkhST0MwClpvVW14bTdLTGEraU5sT2xCcGtR
            bEdReUlFRmZQMXpORDVuU0pZOWhoS0EKLS0tIEdVS2F6VzFFNzlVMTdSTDVjUGdG
            TlRpTFJnN0g1OTcyK1lVSENmcUVxVkkKAe3JGsdmpdRpEP8PYXgSEimHAqnq75R9
            ivUZ9OK8mONp5D3RLWnkfvmb+TKnWaDhb28Kn04ofFrVYGEijmEnYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T21:17:36Z"
    mac: ENC[AES256_GCM,data:1By3wvTkO0p15y2vpUf7bC+yIk4V6jrZHiTARAVy9OFXFhRiBoniqdTKUxoUYZA2bdlNZpoZ/91FQicITAOMh2I2+UhUwN4Z0LpwzI7rgldAot0udeqcCODHIG5NFiCM5rGAPqQr8iH7DtXW0UdO2lbfFGwBwPyfVVXkQzUX93U=,iv:6hjCaHBRhzM+crIpC9WzV5nl8dfdZvDstB901Iyc6Aw=,tag:VqFe9HsXsQqd/zJ7mEs2eg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
