apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:M80JxhDhI0OR7YLXxbhkWNlxnqZTsG77557hwA+lT4FyTV6F,iv:2NQtEhy3cvlB/NVep5CXXCrgIKrjtEiZBfxlX+VP8eg=,tag:ywNs0VF/M8VBpOc37l6wJg==,type:str]
    credentials.json: ENC[AES256_GCM,data:I8pGW/IjVY6Rf+4KrvyR9QhhIjDmDLxUj6Twhbn7MlGHn2rSN+Jk4/BO9l0lYmhJjO/SbLsWYaokCHOiMyVUreWgZGt3HnoJVaKvooa5jjD7PbOoevzctPjUmjfzdj7bVEdka73+oEKL/YLtPi6HdWNSkkeDdEmXgQyHcnferexRmRPXe0phieBcnftRVLdtN5Zc4q7+w2u83Ggxf2nHVFG6AuGbZQN3tWM7q5lCaA==,iv:70JNoAJsM4iTwCr5GQSOlrsv9PGVGkkismONnhAA1xY=,tag:Hl1/UWJKGRDmtyu8Rmu5pQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7f2np2gjaga5zusg7tltae997ft8ha4zglm5qftn3snx8xyefrscdxg7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieDhlb25DTjFmb2dMbXAv
            cnkzZjRweEFrVW4vQnJpVU8rbGpRWkV1RENNCkJkeEFzRWZHcy85bFR4UHhZMUlw
            VDlEam51Rm05a0NCNUEwLytVOUtMRHMKLS0tIFFKbTJ6aFRxSUxzZk45UXROOFdr
            bEpGMENsWUcxSDR4M3JreHl4S2xjaWcK1TqLK6dzkPnzBa1NIuSzPf1WAzyfk0fL
            rZ2GXEteZe+B0ZyDMb5efFvjt9eb730VtSytrs2cWRPP2P88nJfPaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T19:53:48Z"
    mac: ENC[AES256_GCM,data:AKS0uSU1ovdkaTviMlNj9IapxQudPZhaexEtilb+bmpcBe7ItdjnxPAyG45x79i8Sxp5Y2fPIGF7poVMhBjru/8yNkZTcR0HGsOsCcb4WUO5Y/OASZbcq/8CPd51ch186WArdw34DW8I9Yucfks/oGxgdCLxagJyTFT5DsENkoM=,iv:4Nh+778NSPCNXQ79X3x9Ohhz6m5gkxpxvXdOx7p5cu4=,tag:SsBDYIMBuRS6C0XjEuodZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
